import {mkdir,readFile,writeFile} from 'node:fs/promises';
import {resolve} from 'node:path';
import sharp from '../../../../../../_design/.tooling/node_modules/sharp/dist/index.cjs';
const base=resolve('web/product/giao-dien-web/diginest');
const src=base+'/source';
await Promise.all(['assets/css','assets/js','assets/img'].map(p=>mkdir(src+'/'+p,{recursive:true})));
const gen='C:/Users/Lenovo/.codex/generated_images/01a10eaa-da04-7222-a55d-c9732e329704/';
await sharp(gen+'exec-be09f3df-cb0d-4451-a68f-fd841e492c3e.png').resize(1672).webp({quality:86}).toFile(src+'/assets/img/hero-desk.webp');
await sharp(gen+'exec-d85492bb-6766-4148-8f2d-3ce815e3fcef.png').resize(1400).webp({quality:84}).toFile(src+'/assets/img/entertainment.webp');
await sharp(gen+'exec-bcd46eb4-e3d5-4ba7-9b66-b96cb7d0933c.png').webp({quality:88}).toFile(src+'/assets/img/products.webp');
const paths={arrow:'M5 12h14m-6-6 6 6-6 6',search:'m21 21-5-5M18 10a8 8 0 1 1-16 0 8 8 0 0 1 16 0',cart:'M3 3h2l3 12h11l3-9H6M9 20h.01M18 20h.01',close:'m6 6 12 12M6 18 18 6',truck:'M2 5h12v12H2zM14 9h5l3 4v4h-8M7 19a2 2 0 1 1-4 0 2 2 0 0 1 4 0M21 19a2 2 0 1 1-4 0 2 2 0 0 1 4 0',return:'M4 10a8 8 0 1 1 0 5M4 4v6h6',shield:'m12 2 8 4v6c0 5-8 10-8 10S4 17 4 12V6zM8 12l3 3 5-6',chair:'M7 3h10v9H7zM4 9v7h16V9M8 16v6M16 16v6M12 16v6',camera:'M3 7h4l2-3h6l2 3h4v14H3zM16 14a4 4 0 1 1-8 0 4 4 0 0 1 8 0',book:'m3 5 9-2 9 2v15l-9-2-9 2zM12 3v15',monitor:'M2 3h20v14H2zM12 17v4M7 21h10',pc:'M5 2h14v20H5zM9 6h6M9 10h6M12 17h.01',home:'m2 11 10-9 10 9M5 9v13h14V9M9 22v-8h6v8',game:'M6 7h12c4 0 6 13 3 14-2 1-4-4-5-4H8c-1 0-3 5-5 4C0 20 2 7 6 7M5 11v5M3 13.5h4M17 12h.01M19 15h.01',phone:'M6 2h12v20H6zM10 18h4',audio:'M3 14v-3a9 9 0 0 1 18 0v3M3 12h4v9H3zM17 12h4v9h-4z',watch:'M8 2h8v4H8zM8 18h8v4H8zM6 6h12v12H6zM12 9v3l2 1',mail:'M2 4h20v16H2zM2 4l10 9L22 4',gift:'M2 8h20v5H2zM4 13v9h16v-9M12 8v14M12 8c-8 0-7-8-3-6l3 6c8 0 7-8 3-6z',tag:'M2 2h10l10 10-10 10L2 12zM7 7h.01'};
const icon=(name)=>`<svg viewBox="0 0 24 24" aria-hidden="true" focusable="false"><path d="${paths[name]}"/></svg>`;
const products=[['wave','TechWave Pro','Wireless headphones',12999,'audio',0,'New'],['nova','NovaFit 3','Everyday smartwatch',8999,'accessories',1,''],['sound','SoundCore Mini','Smart speaker',4999,'home',2,''],['racer','X-Racer Elite','Precision gaming mouse',5999,'gaming',3,''],['pixel','Pixeluxe 9','Unlocked smartphone',69900,'mobile',4,''],['lens','Focus One','Mirrorless camera',45900,'camera',5,'']];
const cards=products.map(([id,name,type,price,cat,sprite,badge])=>`<article class="product" data-id="${id}" data-name="${name}" data-type="${type}" data-price="${price}" data-category="${cat}" data-sprite="${sprite}"><div class="product-art">${badge?`<span class="pill">${badge}</span>`:''}<div class="device device-${sprite}" role="img" aria-label="${name}, ${type.toLowerCase()}"></div></div><div class="product-info"><h3>${name}</h3><p>${type}</p><div class="product-bottom"><strong>$${(price/100).toFixed(2)}</strong><button type="button" class="add-product" data-add="${id}" aria-label="Add ${name} to cart" disabled>${icon('cart')}</button></div></div></article>`).join('\n');
const work=[['chair','Work From Home','audio'],['camera','Creative Studio','camera'],['book','Student Space','accessories'],['monitor','Minimal Desk','home'],['pc','Pro Setup','gaming']].map(([i,n,c])=>`<a class="workspace" href="#products" data-filter="${c}"><span class="workspace-icon">${icon(i)}</span><span>${n}${icon('arrow')}</span></a>`).join('');
const cats=[['phone','Mobile Devices','mobile'],['home','Smart Home','home'],['game','Gaming Gear','gaming'],['audio','Audio','audio'],['watch','Accessories','accessories'],['camera','Cameras','camera']].map(([i,n,c])=>`<a href="#products" class="category" data-filter="${c}"><span>${icon(i)}</span>${n}</a>`).join('');
await writeFile(src+'/index.html',`<!doctype html>
<html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="description" content="DigiNest — discover thoughtfully chosen tech for work, play and everything in between."><title>DigiNest — Build Your Digital World</title><link rel="stylesheet" href="assets/css/style.css"><script src="assets/js/main.js" defer></script></head>
<body><a class="skip-link" href="#main">Skip to main content</a>
<div class="announcement">A little upgrade. A whole new possibility. <span>Free shipping on orders $99+</span></div>
<header class="header"><a class="brand" href="#top" aria-label="DigiNest home">DIGI<span>NEST</span><i></i></a><button type="button" class="menu-toggle icon-button" aria-label="Open navigation" aria-expanded="false" aria-controls="navigation" hidden><svg viewBox="0 0 24 24" aria-hidden="true" focusable="false"><path d="M3 6h18M3 12h18M3 18h18"/></svg></button><nav id="navigation" aria-label="Main navigation"><a href="#workspaces">Shop by workspace</a><a href="#products">Bestsellers</a><a href="#offers">Explore deals</a></nav><div class="header-actions"><label class="search">${icon('search')}<span class="sr-only">Search products</span><input id="search" type="search" placeholder="Search tech…" autocomplete="off"></label><button class="cart-toggle icon-button" type="button" aria-label="Open cart, 0 items" disabled>${icon('cart')}<span id="cart-count">0</span></button></div></header>
<main id="main" tabindex="-1"><section class="hero" id="top" aria-labelledby="hero-title"><div class="hero-copy"><p class="eyebrow">GOOD TECH. GREAT POSSIBILITIES.</p><h1 id="hero-title">Build Your<br><span>Digital World</span></h1><p class="hero-intro">Everything you need to work,<br>play, create and connect.</p><div class="hero-buttons"><a class="button button-orange" href="#workspaces">Shop All Categories ${icon('arrow')}</a><a class="button button-outline" href="#offers">Explore Deals</a></div><div class="hero-perks"><div>${icon('truck')}<p><strong>Free Shipping</strong><span>On orders over $99</span></p></div><div>${icon('return')}<p><strong>30-Day Returns</strong><span>Room to change your mind</span></p></div><div>${icon('shield')}<p><strong>Thoughtful Selection</strong><span>Tech for your everyday</span></p></div></div></div></section>
<div class="shop-shell"><section class="workspaces section" id="workspaces"><div class="section-heading"><div><p class="eyebrow">MADE FOR YOUR EVERYDAY</p><h2>Shop By Workspace</h2></div><a class="text-link" href="#products" data-filter="all">View all ${icon('arrow')}</a></div><div class="workspace-grid">${work}</div></section>
<section class="promotions section" id="offers" aria-label="Featured collections"><div class="entertainment"><div><p class="eyebrow">MAKE ROOM FOR MORE</p><h2>Entertainment<br>Unleashed</h2><p>Premium tech for movies,<br>music and beyond.</p><a href="#products" data-filter="audio" class="button button-orange">Explore Entertainment ${icon('arrow')}</a></div></div><div class="bundle"><p class="eyebrow">BETTER TOGETHER</p><h2>Bundle Builders</h2><p>More tech. More value.<br>Your soundtrack, everywhere.</p><button type="button" class="text-link" id="add-bundle" disabled>Add audio duo · $179.98 ${icon('arrow')}</button><div class="bundle-art" aria-hidden="true"><div class="device device-0"></div><div class="device device-2"></div></div></div></section>
<nav class="categories section" aria-label="Product categories">${cats}</nav>
<section class="bestsellers section" id="products"><div class="section-heading"><div><p class="eyebrow">YOUR NEXT FAVOURITE</p><h2 id="product-heading">Bestsellers</h2></div><a href="#products" class="text-link" data-filter="all">View all ${icon('arrow')}</a></div><div class="filter-bar" hidden><span id="filter-description"></span><button type="button" id="clear-filter">Clear filters ×</button></div><div class="product-grid">${cards}</div><p id="no-results" hidden>No products found. Try another search or clear your filters.</p><noscript><p class="notice">Product browsing works without JavaScript. Enable JavaScript to search and use the cart.</p></noscript><p class="catalog-note">Concept store · sample products and prices</p></section>
<section class="benefits section" aria-label="Shopping information"><a href="#guide">${icon('book')}<span><strong>Tech, Made Simple</strong><small>Find your everyday setup</small><u>Read the guide</u></span></a><a href="#shipping">${icon('truck')}<span><strong>Easy Delivery</strong><small>Free on orders $99+</small><u>Shipping details</u></span></a><a href="#returns">${icon('return')}<span><strong>Room to Decide</strong><small>Explore our sample policy</small><u>Returns information</u></span></a><a href="#demo-info">${icon('shield')}<span><strong>Clear Checkout</strong><small>Review before you commit</small><u>How this demo works</u></span></a></section>
<section class="newsletter section" aria-labelledby="newsletter-title"><div class="newsletter-copy">${icon('mail')}<div><h2 id="newsletter-title">Stay Ahead in Tech</h2><p>A little inspiration for your next upgrade.</p></div></div><div class="newsletter-form"><label for="email">Email address</label><div><input id="email" type="email" placeholder="Enter your email" disabled><button class="button button-orange" type="button" disabled>Subscribe</button></div><small>Demo only — newsletter signup is not connected.</small></div></section>
<section class="information section" aria-label="Store guide and policies"><details id="guide"><summary>Find your everyday setup</summary><p>Choose headphones for focused work, a smart speaker for your home, or a camera for your next creative project. Use the categories above to explore this six-product concept collection.</p></details><details id="shipping"><summary>Shipping & delivery</summary><p>Sample policy: delivery costs $5.99 for orders below $99, and is free from $99. The cart uses these example rates. No real delivery service is connected.</p></details><details id="returns"><summary>Returns information</summary><p>Sample policy: a 30-day return window. Replace this with your actual return terms before publishing a real store.</p></details><details id="demo-info"><summary>About this concept store</summary><p>The cart, quantities, search and category filters work locally. Checkout reviews your selection only. No payment is taken, no order is submitted, and there is no stock or account service. Product names, prices and policies are examples.</p></details></section></div></main>
<footer class="footer"><div><a class="brand" href="#top">DIGI<span>NEST</span><i></i></a><p>Good tech. Great possibilities.</p></div><div><h2>Shop</h2><a href="#workspaces">Workspaces</a><a href="#products" data-filter="all">All products</a><a href="#offers">Bundles</a></div><div><h2>Help & Support</h2><a href="#shipping">Delivery information</a><a href="#returns">Returns</a><a href="#guide">Shopping guide</a></div><div><h2>Company</h2><a href="#demo-info">About DigiNest</a><p>Independent concept store.<br>Made for your digital world.</p></div><div class="footer-bottom"><span>© 2026 DigiNest · Concept storefront</span><span>Checkout demo · no payments processed</span></div></footer>
<dialog id="cart" aria-labelledby="cart-title"><div class="cart-header"><div><p class="eyebrow">YOUR NEXT UPGRADE</p><h2 id="cart-title">Your Cart <span id="cart-title-count">(0)</span></h2></div><button type="button" class="icon-button" id="close-cart" aria-label="Close cart">${icon('close')}</button></div><div class="cart-body"><div id="cart-empty">${icon('cart')}<h3>Your world is waiting.</h3><p>Add something you love to get started.</p><button type="button" class="button button-orange" id="continue-shopping">Keep exploring ${icon('arrow')}</button></div><div id="cart-lines"></div><div id="checkout-review" hidden tabindex="-1"><h3>Review your selection</h3><p>This is a demo checkout. No payment will be taken and no order will be placed.</p><p id="review-summary"></p><button type="button" class="text-link" id="back-to-cart">← Back to your cart</button></div></div><div class="cart-summary" hidden><p id="shipping-message"></p><div><span>Subtotal</span><strong id="subtotal">$0.00</strong></div><div><span>Shipping</span><strong id="shipping-total">$0.00</strong></div><div class="grand-total"><span>Total</span><strong id="total">$0.00</strong></div><button type="button" id="checkout" class="button button-orange">Review Order ${icon('arrow')}</button><small>Demo checkout · no payment required</small></div></dialog><p class="toast" id="toast" role="status" aria-live="polite"></p><p class="sr-only" id="cart-status" aria-live="polite"></p></body></html>\n`);
let guide=await readFile('web/product/giao-dien-web/docs/customer-guide.en.md','utf8');
guide=guide.replace('# Forge Zone customer guide','# DigiNest customisation guide').replaceAll('reduced motion support','accessible interaction').replaceAll('reduced motion','keyboard navigation').replaceAll('reduced-motion','keyboard').replace(/\[[A-Z][A-Z0-9 ,/.:"—–\-\s]*\]/g,'information you provide (ask me if missing)');
const maps=[['index.html','DIGI','Brand logo text'],['index.html','Build Your','Hero headline'],['index.html','data-price=','Integer-cent prices; never use decimal dollars here'],['index.html','data-category=','Category metadata; keep filter keys consistent'],['assets/css/style.css','--orange:','Orange accent token'],['assets/css/style.css','--cream:','Main background token'],['assets/js/main.js','const FREE_SHIPPING = 9900;','Free shipping threshold in cents'],['assets/js/main.js','const SHIPPING = 599;','Shipping charge in cents']];
await writeFile(base+'/reviews/1.0.0/doc-map.json',JSON.stringify(maps));
await writeFile(src+'/CUSTOMISE.md',guide+'\n## DigiNest specifics\n\nThe catalog has six fictional products. Cart and search run locally with JavaScript; payments, stock, accounts and newsletter subscriptions are not connected. Product names, USD prices, return promises and delivery rates must be replaced before a real launch. Cart prices are read from integer-cent data-price attributes in index.html. Update product metadata and visible labels together. The audio duo adds TechWave Pro and SoundCore Mini at their current prices; update its displayed total whenever either price changes. The demo shipping rate is $5.99 below $99, free from $99.\n\nGenerated images are in assets/img: hero-desk.webp, entertainment.webp, products.webp. The product atlas uses a three-column, two-row grid; keep its positions or update the device-0 through device-5 CSS rules. Product photos are conceptual, not verified photographs of merchandise. The hero image crops on narrower screens; keep its right-hand devices away from text. Heavy filters and fixed background attachment should be avoided.\n\nCart storage key: diginest-cart-v1. Quantity limit: 99 per product. Changing IDs invalidates old stored items. localStorage may be blocked or temporary in file:// or private browsing. Connect a trusted backend and payment provider before taking orders; do not collect payment details in this static page.\n\n## Literal edit map\n\nMAP_PENDING\n');
await writeFile(src+'/README.md',`# DigiNest 1.0.0\n\nA standalone technology ecommerce concept in plain HTML, CSS and JavaScript.\n\n## Included\nRead CUSTOMISE.md first for ten setup steps, twelve AI prompts and the product-specific edit map. The six core files are accompanied by three local WebP images. No framework, build process, external script, tracking, network font or API is required.\n\n## Open\nExtract the entire ZIP and open index.html. You may also serve the folder with any static server. Keep assets beside index.html.\n\n## Working features\nSearch and category filters, mobile navigation, a keyboard-accessible cart dialog, add/remove, quantities 1–99, exact integer-cent USD totals and sample shipping calculation. Cart is saved in localStorage when available. Storage failures do not stop the cart.\n\n## Demo boundaries\nCheckout only reviews the selection; no order or payment is submitted. Newsletter controls are visibly disabled. No accounts, backend, stock verification, taxes, payment gateway or fulfilment. All six product names, images, prices, delivery and returns policies are illustrative. The audio bundle has no discount.\n\n## Customise\nCopy text and product metadata in index.html, palette and system font in assets/css/style.css, shipping/storage rules in assets/js/main.js. All assets are relative and work offline. Without JavaScript all products remain visible, anchors and policy details work, and cart/search cannot operate.\n\n## Testing\nSee the product review folder for recorded browser tests. Supported implementation targets modern Chromium and Firefox with native dialog. Safari has not been tested.\n\n## Licence\nRead LICENCE.txt. Copyright owner and final raster-image commercial terms require the product owner's confirmation before commercial release.\n`);
await writeFile(src+'/LICENCE.txt',`DigiNest licence\n\n1. Permission\nThe intended template licence is perpetual, commercial and non-exclusive, subject to the product owner completing the ownership and raster asset terms below before sale.\n\n2. Permitted use\nUse the licensed template in unlimited projects, including client projects, and modify it freely. Attribution is not required.\n\n3. Restrictions\nDo not resell the template files themselves, list them on another marketplace or include them in a competing template collection.\n\n4. Demo content\nDigiNest and the product names, prices and policies are fictional demonstration content. Replace them before publication. The three images were generated for this concept. They are not verified merchandise photographs. Commercial raster-image terms remain pending the product owner's approval; this document does not independently grant those rights.\n\n5. Fonts\nThis template uses local system fonts only (Segoe UI, Arial and sans-serif fallback). No font file is distributed or fetched. The user's installed fonts remain covered by their own system licences.\n\n6. Ownership\nCopyright owner: OWNER TO BE CONFIRMED BY PRODUCT OWNER. Copyright remains with the author; a template licence grants use, not ownership. Complete this owner field before commercial release.\n\n7. No warranty\nProvided as is without warranty. The user is responsible for verifying content, integrations and suitability. No payment, stock or order service is included.\n\nIf you are unsure whether a use is allowed, ask. The answer is usually yes.\n`);
await writeFile(base+'/README.md',`# DigiNest\n\nSource: source/ · Package: diginest.zip · Version: 1.0.0\n\nUser brief: replace the deleted Aurora product with the tech ecommerce reference; include a functional cart. Scope is this product only, no shared catalog or deployment. Palette deep teal, warm cream and orange; generated imagery, workspace tiles, entertainment feature and six-product catalog.\n\nApproved scope exceptions from WEB-STATIC-1: W01 extra local image files; W03 generated raster photography; W05 local search, filtering and functional persistent cart explicitly required by ecommerce brief; W06 image-containing ZIP exceeds the static SVG limit. Other safeguards apply. Checkout remains a labelled review demo because no real gateway/backend was requested or supplied.\n\nAssumptions: fictional DigiNest branding, English content to match reference, six sample products and USD prices, sample $5.99 shipping below $99. No real ratings, reviews, financing claims or account system.\n`);
console.log('DigiNest HTML, docs and assets created.');
