const fs=require('node:fs'),path=require('node:path');const root='C:/Users/Lenovo/.codex/worktrees/music-app-release/2A';const product='web/product/giao-dien-web/music-app';
for(const f of ['source','music-app.zip'])fs.cpSync(path.join(product,f),path.join(root,product,f),{recursive:true});
const entry=`  t21: {
    slug: 'music-app', cat: 'saas', version: '1.0.0',
    specs: {
      vi: [['Định dạng', 'HTML/CSS/JavaScript thuần'], ['Trong gói', '12 file, 5 ảnh WebP và 1 WAV gốc'], ['Âm thanh', 'Một bản demo tổng hợp 3:09 cho mọi bài'], ['Tương tác', 'Tìm kiếm, phát, seek, volume, yêu thích và theo dõi trong phiên'], ['Tài liệu', '10 bước, 12 prompt AI, giấy phép Forge zone'], ['Phạm vi', 'Không tài khoản, backend hoặc streaming']],
      en: [['Format', 'Plain HTML/CSS/JavaScript'], ['Package', '12 files, 5 WebP images and 1 original WAV'], ['Audio', 'One original 3:09 synthesized demo for every selection'], ['Interaction', 'Search, playback, seek, volume, session favourites and follow'], ['Documentation', '10 steps, 12 AI prompts, Forge zone licence'], ['Scope', 'No accounts, backend or streaming']],
      zh: [['格式', '纯 HTML/CSS/JavaScript'], ['文件包', '12 个文件、5 张 WebP 与 1 个原创 WAV'], ['音频', '所有选择播放同一个 3:09 原创合成示例'], ['交互', '搜索、播放、进度、音量、会话收藏与关注'], ['文档', '10 个步骤、12 个 AI 提示词与 Forge zone 许可'], ['范围', '不含账号、后端或流媒体']],
    },
    copy: {
      vi: { name: 'Music App', desc: 'Giao diện âm nhạc retro nền kem, coral và cobalt: playlist, album, hồ sơ nghệ sĩ, trình phát và thư viện. Năm ảnh tự tạo; âm thanh demo gốc 3:09, tìm kiếm cục bộ, yêu thích và theo dõi trong phiên. Reveal theo cuộn hữu hạn; không backend, tài khoản hoặc streaming.', tags: ['Âm nhạc', 'Retro', 'Ảnh tự tạo'] },
      en: { name: 'Music App', desc: 'A cream, coral and cobalt retro music interface with playlist, album, artist, player and library cards. Five original generated images, a 3:09 original audio demo, local search and session favourites/follow. Finite scroll reveals; no backend, accounts or streaming.', tags: ['Music', 'Retro', 'Original imagery'] },
      zh: { name: 'Music App', desc: '奶油白、珊瑚色与钴蓝复古音乐界面，包含播放列表、专辑、艺人、播放器与音乐库。五张原创生成图片、3:09 原创示例音频、本地搜索及会话收藏与关注。有限滚动渐显，不含后端、账号或流媒体。', tags: ['音乐', '复古', '原创图片'] },
    },
  },
`;
let f=path.join(root,'web/src/lib/real-templates.ts'),s=fs.readFileSync(f,'utf8');if(s.includes('  t21:'))throw Error('Occupied t21');fs.writeFileSync(f,s.replace('export const REAL_TEMPLATES: Record<string, RealTemplate> = {','export const REAL_TEMPLATES: Record<string, RealTemplate> = {\n'+entry));
const guide={vi:{intro:'Giao diện âm nhạc retro với ảnh tự tạo và trình phát demo cục bộ.',notes:'### Bắt đầu\nGiải nén đủ 12 file, mở index.html và giữ assets/ bên cạnh. CUSTOMISE.md có bảng sửa đã đếm, 10 bước và 12 prompt AI.\n\n### Nội dung và âm thanh\nSửa nhãn HTML và tracks trong assets/js/main.js đồng thời. Tên nghệ sĩ và thời lượng danh sách là hư cấu; mọi lựa chọn phát cùng assets/audio/demo.wav dài 3:09. Thay bằng bản ghi được phép dùng trước khi tạo catalog thật.\n\n### Ảnh và tương tác\nNăm WebP ở assets/img/. Giấy phép Forge zone cho dùng ảnh trong website cá nhân/khách hàng, không bán hay phân phối ảnh riêng lẻ. Yêu thích và theo dõi chỉ trong phiên. Không tài khoản hoặc streaming. Token màu/font ở đầu CSS; không cần mạng. Reveal mặc định bật và hữu hạn.'},en:{intro:'A retro music interface with original artwork and a local demo player.',notes:'### Start\nExtract all 12 files, open index.html and keep assets/ beside it. CUSTOMISE.md contains a counted edit map, ten steps and twelve AI prompts.\n\n### Content and audio\nEdit HTML labels and the tracks array in assets/js/main.js together. Artist names and list durations are fictional; every selection plays the same 3:09 assets/audio/demo.wav. Replace it with an authorised recording before offering a real catalogue.\n\n### Images and interaction\nFive WebP images live in assets/img/. Forge zone permits personal/client website use, prohibiting standalone image resale or redistribution. Favourites/follow last for the page session. No accounts or streaming. Colour/font tokens start the CSS; no network dependency. Finite reveals default on.'},zh:{intro:'复古音乐界面，包含原创图片与本地示例播放器。',notes:'### 开始\n完整解压 12 个文件，打开 index.html 并保留旁边的 assets/。CUSTOMISE.md 包含精确修改表、十个步骤与十二个 AI 提示词。\n\n### 内容与音频\n同步修改 HTML 标签与 assets/js/main.js 的 tracks。艺人和列表时长为虚构；所有选择播放同一个 3:09 assets/audio/demo.wav。发布真实目录前换成获许可录音。\n\n### 图片与交互\n五张 WebP 位于 assets/img/。Forge zone 许可用于个人与客户网站，禁止独立出售或分发图片。收藏与关注仅在当前会话有效。不含账号或流媒体。颜色与字体位于 CSS 开头；无需网络。有限渐显默认开启。'}};
f=path.join(root,'web/src/lib/template-guides.ts');s=fs.readFileSync(f,'utf8');fs.writeFileSync(f,s.replace('export const TEMPLATE_GUIDES: Record<string, Record<LangCode, TemplateGuide>> = {','export const TEMPLATE_GUIDES: Record<string, Record<LangCode, TemplateGuide>> = {\n  "music-app": '+JSON.stringify(guide,null,2)+',\n'));
const demo=path.join(root,'web/public/demos/music-app');fs.mkdirSync(demo,{recursive:true});fs.cpSync(path.join(product,'source/assets'),path.join(demo,'assets'),{recursive:true});s=fs.readFileSync(path.join(product,'source/index.html'),'utf8');fs.writeFileSync(path.join(demo,'index.html'),s.replace('<head>','<head><base href="/demos/music-app/">'));
fs.mkdirSync(path.join(root,'web/.vercel'),{recursive:true});fs.copyFileSync('web/.vercel/project.json',path.join(root,'web/.vercel/project.json'));
fs.writeFileSync(path.join(product,'reviews/1.0.0/catalog-entry.txt'),entry);
console.log('Music App only: source, ZIP, t21 SaaS slot, three-language guide and demo copied into production checkout.');
