import {mkdirSync,writeFileSync,readFileSync} from 'node:fs';
const root='web/product/giao-dien-web/vybe';
for(const p of ['source/assets/css','source/assets/js','source/assets/img','reviews/1.0.0','design']) mkdirSync(`${root}/${p}`,{recursive:true});
const products=[['edge','Edge Hoodie','Ivory / geometric','68','Coral, black and emerald graphics on an oversized ivory hoodie.'],['bloom','Bloom Tee','Ivory / botanical','38','A relaxed ivory tee with a bold botanical print.'],['noir','Orbit Tee','Washed black','42','Cream orbital artwork meets a washed black everyday fit.'],['wave','Wave Crew','Emerald green','58','An emerald crewneck with flowing monochrome artwork.'],['solar','Solar Tee','Butter / cobalt','38','A butter yellow tee with a bright cobalt sun print.']];
const image=(p,cls='',lazy=true)=>`<img class="${cls}" src="assets/img/${p[0]}.webp" width="1024" height="1536" alt="Model wearing the ${p[1]} in ${p[2]}" ${lazy?'loading="lazy"':'fetchpriority="high"'}>`;
const html=`<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>VYBE — Wear your own energy</title><meta name="description" content="Graphic streetwear with an independent point of view. Discover five statement pieces from VYBE."><meta property="og:title" content="VYBE — Wear your own energy"><meta property="og:description" content="Five graphic streetwear pieces. Find your next everyday statement."><meta property="og:type" content="website"><link rel="stylesheet" href="assets/css/style.css"><script src="assets/js/main.js" defer></script></head>
<body><a class="skip-link" href="#main">Skip to content</a>
<header class="site-header"><button class="menu-toggle" type="button" aria-controls="site-nav" aria-expanded="false">Menu</button><nav class="site-nav" id="site-nav" aria-label="Main navigation"><a href="#collection">Shop</a><a href="#collection">Collections</a><a href="#about">About</a><a href="#contact">Contact</a></nav><a class="brand" href="#main" aria-label="VYBE home">VYBE<span>®</span></a><div class="header-actions"><a class="small-link" href="#collection">Explore the drop ↗</a><button class="bag-toggle" type="button" aria-controls="bag-dialog">Bag <span data-bag-count>0</span></button></div></header>
<main id="main" tabindex="-1"><section class="hero" aria-labelledby="hero-title"><h1 id="hero-title"><span class="headline-left"><em>Own the</em> <strong>EDGE</strong></span><span class="headline-right"><em>Keep the</em> <strong>VYBE</strong></span></h1><div class="hero-panel"><div class="hero-copy"><p class="eyebrow">THE NEW EXPRESSION / DROP 01</p><h2>Where art meets<br>your everyday.</h2><p>Big graphics. Easy silhouettes.<br>A little more you.</p><a class="pill" href="#collection">Shop the drop <span aria-hidden="true">↗</span></a><div class="drop-note"><span class="note-star" aria-hidden="true">✳</span><p>Wear it your way.<br><strong>Five pieces. No rules.</strong></p></div></div><div class="brush" aria-hidden="true"></div><div class="model-stage" aria-label="Selected streetwear product">${products.map((p,i)=>`<div class="model-slide ${i===0?'is-current':''}" data-slide="${i}" ${i?'aria-hidden="true" inert':''}>${image(p,'hero-model',false)}</div>`).join('')}</div><aside class="hero-side"><ul class="values"><li><b aria-hidden="true">↗</b>Future<br>threads</li><li><b aria-hidden="true">✳</b>Original<br>graphics</li><li><b aria-hidden="true">◷</b>Small<br>collection</li></ul><p class="featured-label">IN THE SPOTLIGHT</p><article class="featured"><div class="featured-image">${image(products[0],'featured-model',false)}<span class="edition">DROP / 01</span></div><div class="featured-caption"><h3 data-name>Edge Hoodie</h3><p data-color>Ivory / geometric</p><button type="button" class="add-button" data-add-selected>Add to bag <span data-price>$68</span></button></div></article></aside></div><div class="hero-bottom"><p class="selected-label"><span class="eyebrow">YOUR CURRENT VYBE</span><strong data-selected-name>Edge Hoodie</strong></p><div class="carousel-controls" aria-label="Product carousel"><button type="button" data-prev aria-label="Previous product">←</button><span data-counter aria-live="polite">01 / 05</span><button type="button" data-next aria-label="Next product">→</button></div><button class="motion-toggle" type="button" aria-pressed="true">Pause motion</button></div><div class="product-picks" aria-label="Choose a product">${products.map((p,i)=>`<button type="button" data-pick="${i}" aria-pressed="${i===0}"><span class="swatch swatch--${p[0]}"></span>${p[1]}</button>`).join('')}</div></section>
<section class="collection" id="collection" aria-labelledby="collection-title"><div class="section-heading"><div><p class="eyebrow">THE EDIT / 001</p><h2 id="collection-title">Good fits.<br><em>Great energy.</em></h2></div><p>Your next favourite starts here.<br>Pick a piece. Make it your own.</p></div><div class="product-grid">${products.map((p,i)=>`<article class="product-card"><button type="button" class="product-art product-art--${p[0]}" data-view="${i}" aria-label="View ${p[1]} in the hero">${image(p)}<span class="product-number">0${i+1}</span><span class="view-label">Try the vybe ↗</span></button><div class="product-info"><div><h3>${p[1]}</h3><p>${p[2]}</p></div><strong>$${p[3]}</strong></div><div class="product-buy"><label>Size <select data-size="${i}" aria-label="Size for ${p[1]}"><option>S</option><option selected>M</option><option>L</option><option>XL</option></select></label><button type="button" data-add="${i}">Add to bag +</button></div></article>`).join('')}</div></section>
<section class="about" id="about"><p class="eyebrow">NOT MADE TO BLEND IN.</p><h2>A canvas for<br><em>your kind of bold.</em></h2><div><p>VYBE is a fictional independent streetwear label exploring colour, shape and self-expression. This first edit pairs graphic artwork with relaxed silhouettes.</p><a class="text-link" href="#collection">Find your expression ↗</a></div><span class="about-mark" aria-hidden="true">V.</span></section>
<section class="contact" id="contact"><div><p class="eyebrow">LET’S TALK THREADS</p><h2>Got a question?<br>Say hey.</h2></div><div><a class="pill pill--dark" href="mailto:hello@example.com">hello@example.com ↗</a><p>Demonstration store. Products, prices and material details are sample content. The bag is saved on this device; checkout and payment are not connected.</p></div></section></main><footer><a class="brand" href="#main">VYBE<span>®</span></a><p>Own the edge. Keep the vybe.</p><small>© 2026 VYBE. Demo label.</small></footer>
<dialog id="bag-dialog" aria-labelledby="bag-title"><div class="bag-heading"><h2 id="bag-title">Your bag</h2><button type="button" data-close-bag aria-label="Close bag">×</button></div><p class="bag-disclaimer">Local demo bag · no payment is collected.</p><div data-bag-items></div><p class="bag-total">Subtotal <strong data-total>$0</strong></p><a class="pill pill--dark" data-enquire href="mailto:hello@example.com">Enquire about these pieces ↗</a><p>Email opens your mail app. It does not place an order.</p></dialog><p class="toast" role="status" aria-live="polite"></p><noscript><p class="noscript-note">Product selection and bag require JavaScript. Browse all five pieces below and email us to enquire.</p></noscript></body></html>`;
writeFileSync(`${root}/source/index.html`,html);
writeFileSync(`${root}/design/products.json`,JSON.stringify(products,null,2));
writeFileSync(`${root}/reviews/1.0.0/BRIEF.md`,'# VYBE — 1.0.0\nNgày 05/10/2026. Thay Meridian (t6) bằng template bán áo streetwear theo ảnh tham chiếu của chủ sản phẩm. Năm mẫu: Edge, Bloom, Orbit, Wave, Solar. Hero người mẫu trung tâm, nền coral, chữ đen lớn, product carousel Morge có hướng, vòng cuối→đầu trực tiếp, giảm chuyển động, swipe. HTML/CSS/JS thuần, ảnh local AI tự tạo. Bag local có size/remove/subtotal, email enquiry; không backend/payment. Ngoại lệ được yêu cầu trực tiếp: W01/W03/W05/W06 (ảnh raster, file bổ sung, carousel/bag, ZIP lớn hơn chuẩn). Không deploy. Catalog giữ ID t6 để không phá liên kết/quyền mua.\n');
writeFileSync(`${root}/source/README.md`,'# VYBE\n\nStart with CUSTOMISE.md for the ten-step guide and twelve AI prompts.\n\nA plain HTML/CSS/JavaScript streetwear template with five original generated model images, a directional product carousel, size selection and a local demonstration bag. Open index.html directly. No build, fonts, CDN or network dependency. Email enquiry opens a mail app; no order, payment, stock or fulfilment system is included. Prices, products and brand are fictional.\n\nEdit colours in assets/css/style.css, product data in assets/js/main.js and cards in index.html together. Replace assets/img/*.webp with your own transparent cutouts, preserving the file names or updating paths. No-JS visitors can browse all cards and use email links. Motion respects the OS preference, URL motion=on/off and a saved preference; it can be paused at any time.\n\nBrowser verification is recorded in reviews outside the customer package. See LICENCE.txt for the existing commercial terms; generated raster assets have their provenance recorded in the delivery report.\n');
writeFileSync(`${root}/source/LICENCE.txt`,readFileSync('web/product/giao-dien-web/meridian/source/LICENCE.txt','utf8'));
let guide=readFileSync('web/product/giao-dien-web/docs/customer-guide.en.md','utf8').replace('# Forge Zone customer guide','# VYBE — customise your streetwear store').replaceAll('360 px','320 px');
guide+='\n\n## VYBE product editing\n\nThe five local WebP cutouts are in assets/img/. Update the products array in assets/js/main.js and matching HTML cards together. Keep filenames, alt text, price and model names consistent. Sizes and bag quantities are stored only in this browser; they are not inventory. Connect a real ecommerce service before accepting payments. Remove the demo notice only after integration. Motion duration is 850ms; images share a fixed stage so copy and controls remain stable. The carousel never advances automatically.\n';
writeFileSync(`${root}/source/CUSTOMISE.md`,guide);
writeFileSync(`${root}/README.md`,'# VYBE\nSource: source/. Delivery: vybe.zip. Demo: /demos/vybe/. Replaces Meridian in catalog slot t6. See reviews/1.0.0 for provenance, exceptions and verification.\n');
