/* Emit an apply_patch document, not a filesystem write. Re-run after source edits
   to refresh the literal search counts in the customer documentation. */
import { readFileSync, existsSync } from 'node:fs';
import { resolve } from 'node:path';

const configs = [
  { slug: 'solenne', name: 'Solenne', slot: 't4', category: 'business', industry: 'Studio chăm sóc da, facial và wellness', audience: 'Chủ studio chăm sóc cá nhân muốn trang giới thiệu dịu, rõ dịch vụ và nhận hỏi lịch qua email', goal: 'Giúp khách chọn ritual và gửi yêu cầu tới studio; không hứa đặt lịch online', sections: 'Hero → cách tiếp cận → ba ritual → quy trình lần đầu → liên hệ → footer', direction: 'Lilac dịu, serif Georgia + Manrope; hero botanical dạng vòm; dịch vụ là các hàng editorial thay cho thẻ', choices: 'Minh họa chai skincare và lá tự vẽ; typography serif nghiêng và danh sách ritual dạng hàng', avoid: 'Không hứa chữa bệnh, không review/ảnh khách thật, không form đặt lịch giả', variance: '7 / 4 / 3', fonts: ['Manrope'], demo: 'Solenne is a fictional skin studio. The Reset (60 minutes), The Restore (75 minutes) and The Conversation (30 minutes) are sample services and durations, not medical advice. Replace them with verified offerings. No studio address, clinical claim, testimonial or treatment price is supplied.', fields: [['index.html', 'Solenne', 'Brand, metadata and accessible brand name; also replace lowercase solenne separately.'], ['index.html', 'solenne.', 'Visible lowercase wordmark in the footer.'], ['index.html', 'solenne<span', 'Header wordmark: change only the text before the span; preserve markup.'], ['index.html', 'Skin rituals,', 'Main headline; keep the em element and use short natural wording.'], ['index.html', 'The Reset', 'Service name and its accessible enquiry label; replace both.'], ['index.html', 'The Restore', 'Service name and its accessible enquiry label; replace both.'], ['index.html', 'The Conversation', 'Service name and its accessible enquiry label; replace both.'], ['index.html', 'minutes', 'Sample durations; replace only after the real services are confirmed.'], ['index.html', 'class="ritual"', 'Complete li service blocks; remove/add whole blocks and review menu anchors.'], ['index.html', 'class="ritual-art"', 'Hero SVG: replace within hero__figure; preserve aspect ratio and add accurate alt text.'], ['index.html', 'class="visit__art"', 'Decorative visit SVG; keep hidden from assistive technology unless informative.']], notes: 'Edit the ritual duration, heading, description and enquiry label together. The lowercase header wordmark includes a separate decorative full-stop span. The illustration uses named SVG gradients; preserve their unique IDs. The contact CTA opens an email app, not a booking system.' },
  { slug: 'meridian', name: 'Meridian', slot: 't6', category: 'business', industry: 'Sourcing, điều phối sản xuất và xuất khẩu B2B', audience: 'Doanh nghiệp thương mại, sourcing và nhà cung cấp cần trình bày năng lực rõ ràng', goal: 'Giải thích phạm vi phối hợp và nhận product brief qua email, không báo giá tự động', sections: 'Hero sourcing → ba năng lực → quy trình → ba nhóm sản phẩm → email brief CTA → footer', direction: 'Cobalt + off-white, Manrope; containers isometric trên route/grid; quy trình split trên nền xanh nhạt', choices: 'Hero container isometric tự tạo; quy trình có bước nối tiếp và ba nhóm sản phẩm bằng minh họa khác nhau', avoid: 'Không chứng nhận logistics, số liệu giao hàng, khách hàng và cảng giả; không catalog live', variance: '6 / 4 / 4', fonts: ['Manrope'], demo: 'Meridian is a fictional sourcing and export-coordination business. The home and living, packaging and textile categories are sample focus areas, not stock listings. Services and process steps are demonstration copy, not logistics commitments. No certifications, delivery guarantees, supplier endorsements, addresses or prices are supplied.', fields: [['index.html', 'Meridian', 'Mixed-case brand in metadata, accessible name and footer notice.'], ['index.html', 'meridian.', 'Visible footer wordmark.'], ['index.html', 'meridian<span', 'Header wordmark: replace its text only; retain the decorative dot span.'], ['index.html', 'FROM YOUR BRIEF.', 'Hero first line. Keep replacement concise and check phone widths.'], ['index.html', 'RIGHT', 'Accent part of the main heading; review the whole h1 block.'], ['index.html', 'class="expertise-list"', 'Three service li blocks; replace headings and descriptions together.'], ['index.html', 'class="product"', 'Complete product-focus article blocks; these are not purchasable products.'], ['index.html', 'class="cargo-art"', 'Hero cargo SVG; keep the responsive hero__figure wrapper.'], ['index.html', 'Home &amp; living', 'HTML-escaped category name; keep valid HTML when editing.'], ['index.html', 'class="process-list"', 'Three ordered process steps; update complete li blocks.']], notes: 'Product focus is not an inventory system or live catalogue. Check sourcing, production and export wording against your actual responsibilities. Keep the contact disclaimer; enquiry does not create a quote or delivery commitment. The header wordmark has a separate decorative dot span.' },
];
const root = resolve('.');
const guide = readFileSync(resolve(root, 'web/product/giao-dien-web/docs/customer-guide.en.md'), 'utf8').replaceAll('\r\n', '\n');
const js = readFileSync(resolve(root, 'web/product/giao-dien-web/solenne/source/assets/js/main.js'), 'utf8');
const patch = [];
function add(path, content) {
  // Generated documents are regenerated through apply_patch, never shell writes.
  const next = content.trimEnd();
  if (!existsSync(resolve(root, path))) {
    patch.push(`*** Add File: ${path}\n${next.split(/\r?\n/).map(line => '+' + line).join('\n')}`);
    return;
  }
  const current = readFileSync(resolve(root, path), 'utf8').trimEnd().replaceAll('\r\n', '\n');
  if (current === next.replaceAll('\r\n', '\n')) return;
  const before = current.split('\n');
  const after = next.split(/\r?\n/);
  let head = 0;
  while (before[head] === after[head] && head < Math.min(before.length, after.length)) head++;
  let tail = 0;
  while (before[before.length - 1 - tail] === after[after.length - 1 - tail] && tail < Math.min(before.length, after.length) - head) tail++;
  const start = Math.max(0, head - 3);
  const contextBefore = before.slice(start, head).map(line => ' ' + line);
  const removed = before.slice(head, before.length - tail).map(line => '-' + line);
  const added = after.slice(head, after.length - tail).map(line => '+' + line);
  const contextAfter = before.slice(before.length - tail, before.length - tail + 3).map(line => ' ' + line);
  patch.push(`*** Update File: ${path}\n@@\n${[...contextBefore, ...removed, ...added, ...contextAfter].join('\n')}`);
}
function customerGuide(name) {
  let text = guide.replace('# Forge Zone customer guide', `# ${name} — your website, step by step`)
    .replace('and replace the information in square brackets.', 'and answer the AI’s questions in plain language. You do not need to fill in code, selectors or technical settings.')
    .replace('I bought a static website template from Forge Zone', `I bought the ${name} static website template from Forge Zone`)
    .replace('template-folder/', `${name.toLowerCase()}/`)
    .replace('copy with the verified information below:', 'copy with verified information. Before editing, ask me for these details; do not treat this list as business data:')
    .replace('Use only these verified destinations:', 'Ask me for the verified destinations below before editing. Use only destinations I confirm:')
    .replace('Apply this brand system while preserving', 'Ask me for the brand system below, allow "keep current", then apply my answers while preserving')
    .replace('The image is intended for\n[LOGO / HERO / SECTION NAME] and I have permission to use it.', 'Ask which section should use the image and confirm my permission to publish it before editing.')
    .replace('into [LANGUAGE].', 'into the language I choose. Ask for the target language before editing; also update the HTML lang attribute.')
    .replace('I want to [ADD / REMOVE] this item or section:\n[DESCRIBE THE SERVICE OR SECTION AND PROVIDE VERIFIED CONTENT].', 'Ask whether I want to add or remove a section or item, which one, and its verified content. Do not edit until I answer.')
    .replace('on\n[HOSTING PROVIDER].', 'on a hosting provider I choose. Ask which provider I am using before giving provider-specific steps.')
    .replace('on\n[HOSTING PROVIDER]. My domain is managed at [DOMAIN OR DNS PROVIDER].', 'on my hosting provider. Ask which host and domain/DNS provider I use before continuing.')
    .replace('Change only this item:\n[DESCRIBE THE EXACT UPDATE].', 'Ask for the exact update I need, then change only that approved item.')
    .replace('- What I expected: [EXPECTED RESULT]', '- Ask what I expected to happen.')
    .replace('- What happened: [ACTUAL RESULT]', '- Ask what actually happened.')
    .replace('- Where it happens: [PAGE, SECTION, DEVICE, BROWSER]', '- Ask which section, device and browser are affected.')
    .replace('- When it started: [LAST CHANGE]', '- Ask when it started and what last changed.')
    .replace('- Any browser error: [EXACT ERROR OR "NONE SEEN"]', '- Ask for any exact browser error, or let me answer "none seen".')
    .replaceAll('360 px', '320 px')
    .replace('at 320 px and on desktop.', 'at 320, 375, 820 and 1440 CSS pixels.');
  const answers = { 'BRAND NAME': 'ask me for my real brand name', 'PRODUCTS OR SERVICES': 'ask for verified products or services', 'TARGET AUDIENCE': 'ask who I want to reach', 'VERIFIED BENEFIT': 'ask for a benefit I can support', 'FOR EXAMPLE: CLEAR, WARM, PROFESSIONAL': 'ask what tone I want', 'EMAIL, PHONE, ADDRESS OR "NOT PUBLIC"': 'ask which contact details may be public', 'WHAT THE VISITOR SHOULD DO': 'ask for the intended visitor action', 'LANGUAGE': 'ask for the required language', 'EMAIL, PHONE, BOOKING URL OR OTHER REAL URL': 'ask for my confirmed primary destination', 'REAL URL OR "REMOVE"': 'ask for a real destination or permission to remove it', 'REAL URLS OR "REMOVE"': 'ask for my public URLs or permission to remove them', 'HEX OR RGB': 'ask for my brand colour, or keep the current colour', 'FONT NAME OR "KEEP CURRENT"': 'ask for my font choice, or keep the current font' };
  text = text.replace(/\[([^\]]+)\]/g, (match, key) => answers[key] ?? match);
  return text.replace('Use the latest website files in this conversation.', 'Use the latest website files I attach. If this is a new chat, ask me to attach all six current files and run Prompt 01 first.')
    .replaceAll('Return complete changed files', 'Ask for any missing input before editing. Return complete changed files with their exact relative destination paths');
}
for (const c of configs) {
  const base = `web/product/giao-dien-web/${c.slug}/source`;
  if (c.slug !== 'solenne') add(`${base}/assets/js/main.js`, js);
  const fields = [...c.fields, ['index.html', 'hello@example.com', 'Replace every visible email and mailto destination with the verified public email.'], ['index.html', 'mailto:hello@example.com', 'Working email links only; they open an email app, never send automatically.'], ['index.html', '<title>', 'Browser title; also update og:title and both description metadata values.'], ['index.html', 'id="contact"', 'Real contact anchor. Keep IDs matched to nav links if renaming.'], ['index.html', 'data-reveal', 'Optional reveal hooks; content remains available with JS disabled.'], ['assets/css/style.css', ':root {', 'Colour, font and spacing tokens are at the start of the file.'], ['assets/css/style.css', '--accent:', 'Main brand accent. Check text, button and focus contrast after changing.'], ['assets/css/style.css', '--font-display:', 'Heading family; change the HTML Google Fonts request if necessary.'], ['assets/css/style.css', '--font-body:', 'Body family and fallbacks; keep readable offline fonts.'], ['assets/js/main.js', '(max-width: 950px)', 'Menu breakpoint; keep matched with the CSS breakpoint.']];
  const table = fields.map(([file, needle, task]) => {
    const source = file.endsWith('main.js') ? js : readFileSync(resolve(root, base, file), 'utf8');
    const count = source.split(needle).length - 1;
    if (!count) throw new Error(`Missing literal ${needle} in ${c.slug}/${file}`);
    return `| \`${file}\` | \`${needle}\` | ${count} | ${task} |`;
  }).join('\n');
  add(`${base}/CUSTOMISE.md`, `${customerGuide(c.name)}\n\n## ${c.name} — exact edit map\n\nCounts below are literal, case-sensitive occurrences in the named file of the supplied 1.0.0 version. They are not line numbers or regex matches. After customising, your counts may change. Search the literal string in a text editor. Preserve the surrounding markup unless the instruction says to replace the complete block.\n\n| File | Search literally | Count | What to do |\n|---|---|---:|---|\n${table}\n\n### Template-specific checks\n\n${c.notes}\n\n${c.demo}\n\nThere is no repeated marquee content in this template. Each list item is a separate editable item. Update accessible labels and SVG titles whenever their visible names change. Google Fonts is the only optional network dependency. To go fully offline, remove its three link elements and use the declared fallback fonts.\n\nOpen the local page after each change, then check desktop (1440 × 900), tablet (820 × 1180), phone (375 × 812) and narrow phone (320 × 740), both sides of the 950 px menu breakpoint and 200% browser zoom. Test Tab, Shift+Tab, Escape, every section link and email destination. Enable reduced motion and disable JavaScript once. If you replace the illustration with a photograph, put it in a local assets folder: that is your customised copy, not an extra file in this original six-file product.\n\nAll prompts are self-contained tasks, not promises that a chat tool can edit your computer. Attach the latest files to each new chat, start with Prompt 01, and apply complete returned files to the named relative paths. No prompt should require you to identify a selector or fill a technical configuration. Before publishing, verify the email address: example.com is a demo destination, not the studio’s inbox.\n`);
  add(`${base}/README.md`, `# ${c.name} — static website template\n\nVersion 1.0.0 · Forge Zone · WEB-STATIC-1 (standards 1.2)\n\nStart with **CUSTOMISE.md**. It contains ten practical steps, twelve copy-ready AI prompts, and a counted search table specific to this template. Editing code or applying complete files returned by your AI tool is required; this is not a hosted no-code editor.\n\n## Open\n\nExtract the complete ZIP and open ${c.slug}/index.html in a browser. Keep assets/css/style.css and assets/js/main.js in their original relative paths. No installation or build is required. Upload the contents of the ${c.slug} folder to the root of any static host. Keep LICENCE.txt and an untouched original backup.\n\n## Included\n\nOne English HTML page, one CSS file, one JavaScript file, CUSTOMISE.md, README.md and LICENCE.txt. All artwork is original inline SVG. Mobile navigation and short reveal transitions are the only JavaScript behaviours. Every CTA is a section anchor or an email link. Email links open the visitor’s email app; they do not send a message automatically.\n\n## Not included\n\nNo backend, booking, checkout, cart, login, live search, inventory, form submission, analytics or data collection. ${c.slug === 'forma' ? 'Project panels are presentation content, not working case-study pages.' : 'The contact action is an enquiry, not an automated reservation or quote.'} The storefront preview video is not embedded in the downloadable template.\n\n## Demo data\n\n${c.demo}\n\nReplace every hello@example.com destination and all demo branding before publishing. Read the exact edit map near the end of CUSTOMISE.md.\n\n## Fonts and offline use\n\n${c.fonts.join(' and ')} ${c.fonts.length > 1 ? 'are' : 'is'} optionally loaded from Google Fonts with display=swap. System fallbacks are declared in CSS. With no network, the page remains readable and usable but typography can differ. No external image or script is required. Font licences and official source links are in LICENCE.txt.\n\n## Verified compatibility\n\nThe release checks run on Windows with actual Chromium and Firefox, at desktop, tablet and phone widths, over HTTP and file:// after ZIP extraction. Safari, Edge and physical mobile devices have not been separately tested; no claim of verified support for them is made. Reduced motion, disabled JavaScript, blocked fonts and keyboard navigation are included in the release checks. This is an internal checklist, not an external accessibility certification.\n\nSee LICENCE.txt for commercial use and redistribution restrictions.\n`);
  let licence = readFileSync(resolve(root, 'web/product/giao-dien-web/kinetiq/source/LICENCE.txt'), 'utf8')
    .replace('KINETIQ', c.name.toUpperCase())
    .replace('The company name, copy and figures in this template are made up. They are there\r\nto show the layout. Replace them before publishing.', c.demo)
    .replace(/Archivo and Archivo Black are loaded[\s\S]*?the SIL Open Font License, not by this licence\./, `${c.fonts.join(' and ')} ${c.fonts.length > 1 ? 'are' : 'is'} loaded from Google Fonts and licensed separately under the SIL Open Font License 1.1. Verified official source:\nhttps://raw.githubusercontent.com/google/fonts/main/ofl/manrope/OFL.txt\n${c.fonts.includes('Barlow Condensed') ? 'https://raw.githubusercontent.com/google/fonts/main/ofl/barlowcondensed/OFL.txt\n' : ''}The fonts are not bundled in the ZIP. Georgia, when used, is a system fallback; it is not supplied or relicensed by this product.`)
    .replace('Copyright in the design and source code remains with the author.', 'Copyright © 2026 Đinh Văn Triển (Forge Zone).\nCopyright in the design and source code remains with the author.')
    .replace(/It is tested in current Chrome, Firefox, Safari\r?\nand Edge, but it cannot be guaranteed to suit every purpose or every browser\./, 'It has been checked on Chromium and Firefox on Windows.\nIt cannot be guaranteed to suit every purpose or every browser. Safari and Edge\nhave not been separately tested. No warranty is made for any AI customisation.');
  add(`${base}/LICENCE.txt`, licence);
  add(`web/product/giao-dien-web/${c.slug}/reviews/1.0.0/BRIEF.md`, `# ${c.name} — brief\n\n- Loại: web-template; hồ sơ WEB-STATIC-1; chuẩn 1.2; sản phẩm 1.0.0.\n- Slug: ${c.slug}; catalog: ${c.slot}; category: ${c.category}.\n- Ngành: ${c.industry}.\n- Người mua: ${c.audience}.\n- Người truy cập: khách hàng tiềm năng của doanh nghiệp sau khi khách thay nội dung.\n- Mục tiêu: ${c.goal}.\n- CTA: anchor tới nội dung/contact, cuối cùng mailto:hello@example.com (đích demo phải thay).\n- Section: ${c.sections}.\n- Hướng thị giác: ${c.direction}.\n- Hai lựa chọn riêng: ${c.choices}.\n- Tránh: ${c.avoid}.\n- Tài sản: SVG tự tạo; không ảnh/logo khách thật. Font nguồn Google Fonts đã đối chiếu OFL.\n- Phạm vi: sáu file, tài liệu, ZIP, QA, preview WebP + video quay trang thực; tích hợp và deploy cửa hàng hiện có.\n- Giá: giữ cấu hình catalog hiện tại, 1.900.000 VND / 79 USD. Không override giá.\n- Giả định: tự chọn tên doanh nghiệp hư cấu và ngành mẫu mới trong phạm vi bổ sung template. Không mở rộng backend.\n- Design skill: variance/motion/density ${c.variance}. Chuẩn người dùng ưu tiên: SVG nội tuyến thay ảnh sinh AI; JS native menu/reveal thay thư viện animation; palette cố định thay theme toggle. Đây là điều chỉnh skill theo chuẩn, không phải ngoại lệ WEB-STATIC-1.\n- Ngoại lệ chuẩn: không đề xuất. Chỉ phát hành khi kiểm tra bắt buộc hoàn thành; luồng tải có quyền thật phải được ghi trung thực.\n`);
}
console.log(patch.length ? `*** Begin Patch\n${patch.join('\n')}\n*** End Patch` : 'UNCHANGED');
